# deploy/helm/aispm/templates/redis-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels: { app: redis }
  template:
    metadata:
      labels: { app: redis }
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}:{{ .Values.redis.tag }}
          command:
            - redis-server
            - --save
            - ""
            - --appendonly
            - "yes"
            - --stop-writes-on-bgsave-error
            - "no"
            - --maxmemory
            - {{ .Values.redis.maxmemory }}
            - --maxmemory-policy
            - allkeys-lru
            - --loglevel
            - warning
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: {{ .Values.redis.storageClass }}
        resources:
          requests:
            storage: {{ .Values.redis.storage }}
