"""
policies/seed.py
─────────────────
Default policy seed data.
Called once at application startup if the policies table is empty.
No side effects on import — seeding only happens when seed_policies() is called.
"""
from __future__ import annotations

from .store import (
    _PROMPT_GUARD_CODE,
    _TOOL_SCOPE_CODE,
    _PII_MASK_CODE,
    _WRITE_APPROVAL_CODE,
    _TOKEN_BUDGET_CODE,
    _OUTPUT_FILTER_CODE,
    _EGRESS_CONTROL_CODE,
    _RAG_RETRIEVAL_CODE,
    _JAILBREAK_DETECT_CODE,
    _tokenise,
    create_policy_raw,
    list_policies,
)

_SEED_DATA = [
    {
        "id": "pg-v3",
        "name": "Prompt-Guard",
        "version": "v3",
        "type": "prompt-safety",
        "mode": "Enforce",
        "status": "Active",
        "scope": "All Production Agents",
        "owner": "security-ops",
        "createdBy": "admin@orbyx.ai",
        "created": "Mar 12, 2026",
        "updated": "2d ago",
        "updatedFull": "Apr 7, 2026 · 09:14 UTC",
        "description": "Detects and blocks adversarial prompt patterns including jailbreaks, role-play overrides, and Base64-encoded bypass attempts before they reach any production model invocation.",
        "affectedAssets": 8,
        "relatedAlerts": 4,
        "linkedSimulations": 2,
        "agents": ["CustomerSupport-GPT", "ThreatHunter-AI", "DataPipeline-Orchestrator"],
        "tools": [],
        "dataSources": [],
        "environments": ["Production"],
        "exceptions": ["staging-test-agent-01"],
        "impact": {"blocked": 4, "flagged": 11, "unchanged": 105, "total": 120},
        "history": [
            {"version": "v3", "by": "admin@orbyx.ai",   "when": "Apr 7, 2026 · 09:14",  "change": "Added Base64 payload detection. Confidence threshold raised to 0.92."},
            {"version": "v2", "by": "sec-eng@orbyx.ai", "when": "Mar 28, 2026 · 14:02", "change": "Expanded jailbreak signature library. Added roleplay framing detection."},
            {"version": "v1", "by": "admin@orbyx.ai",   "when": "Mar 12, 2026 · 10:30", "change": "Initial policy created. Basic injection pattern matching."},
        ],
        "logic_code": _PROMPT_GUARD_CODE,
        "logic_language": "rego",
    },
    {
        "id": "ts-v2",
        "name": "Tool-Scope",
        "version": "v2",
        "type": "tool-access",
        "mode": "Enforce",
        "status": "Active",
        "scope": "All Agents — Production",
        "owner": "platform-eng",
        "createdBy": "platform@orbyx.ai",
        "created": "Mar 14, 2026",
        "updated": "3d ago",
        "updatedFull": "Apr 6, 2026 · 11:30 UTC",
        "description": "Restricts which tools each agent role may invoke. Deny-by-default; explicit allowlist per scope + posture threshold check before any side-effect tool is executed.",
        "affectedAssets": 12,
        "relatedAlerts": 1,
        "linkedSimulations": 3,
        "agents": ["CustomerSupport-GPT", "ThreatHunter-AI", "DataPipeline-Orchestrator", "ReportGen-AI"],
        "tools": ["file.read", "file.write", "gmail.send_email", "calendar.write", "db.query"],
        "dataSources": [],
        "environments": ["Production", "Staging"],
        "exceptions": [],
        "impact": {"blocked": 7, "flagged": 5, "unchanged": 88, "total": 100},
        "history": [
            {"version": "v2", "by": "platform@orbyx.ai", "when": "Apr 6, 2026 · 11:30", "change": "Added db.query and web.search to allowlist. Tightened posture thresholds."},
            {"version": "v1", "by": "platform@orbyx.ai", "when": "Mar 14, 2026 · 09:00", "change": "Initial tool scope policy. Read-only tools permitted at posture < 0.40."},
        ],
        "logic_code": _TOOL_SCOPE_CODE,
        "logic_language": "rego",
    },
    {
        "id": "pm-v1",
        "name": "PII-Mask",
        "version": "v1",
        "type": "privacy",
        "mode": "Enforce",
        "status": "Active",
        "scope": "All Output Streams",
        "owner": "privacy-team",
        "createdBy": "dpo@orbyx.ai",
        "created": "Mar 20, 2026",
        "updated": "5d ago",
        "updatedFull": "Apr 4, 2026 · 16:22 UTC",
        "description": "Detects and redacts personally identifiable information (PII) from all LLM outputs before delivery to end users. Covers emails, SSNs, phone numbers, and financial data.",
        "affectedAssets": 6,
        "relatedAlerts": 0,
        "linkedSimulations": 1,
        "agents": [],
        "tools": [],
        "dataSources": ["customer-db", "hr-records"],
        "environments": ["Production"],
        "exceptions": ["internal-analytics-agent"],
        "impact": {"blocked": 0, "flagged": 3, "unchanged": 97, "total": 100},
        "history": [
            {"version": "v1", "by": "dpo@orbyx.ai", "when": "Mar 20, 2026 · 10:00", "change": "Initial PII masking policy. Regex + OPA hybrid detection."},
        ],
        "logic_code": _PII_MASK_CODE,
        "logic_language": "rego",
    },
    {
        "id": "wa-v2",
        "name": "Write-Approval",
        "version": "v2",
        "type": "tool-access",
        "mode": "Enforce",
        "status": "Active",
        "scope": "Write-Side-Effect Tools",
        "owner": "security-ops",
        "createdBy": "admin@orbyx.ai",
        "created": "Mar 22, 2026",
        "updated": "4d ago",
        "updatedFull": "Apr 5, 2026 · 14:10 UTC",
        "description": "Enforces human-in-the-loop approval for all write-side-effect tool calls (file.write, gmail.send_email, calendar.write) when posture score exceeds 0.20.",
        "affectedAssets": 5,
        "relatedAlerts": 2,
        "linkedSimulations": 1,
        "agents": ["CustomerSupport-GPT", "ReportGen-AI"],
        "tools": ["file.write", "gmail.send_email", "calendar.write"],
        "dataSources": [],
        "environments": ["Production"],
        "exceptions": [],
        "impact": {"blocked": 3, "flagged": 8, "unchanged": 89, "total": 100},
        "history": [
            {"version": "v2", "by": "admin@orbyx.ai",   "when": "Apr 5, 2026 · 14:10", "change": "Added calendar.write to approval scope. Lowered approval threshold to 0.20."},
            {"version": "v1", "by": "platform@orbyx.ai","when": "Mar 22, 2026 · 09:30", "change": "Initial write-approval policy. Covered file.write and gmail.send."},
        ],
        "logic_code": _WRITE_APPROVAL_CODE,
        "logic_language": "json",
    },
    {
        "id": "tb-v1",
        "name": "Token-Budget",
        "version": "v1",
        "type": "rate-limit",
        "mode": "Enforce",
        "status": "Active",
        "scope": "All Tenants — Sessions",
        "owner": "platform-eng",
        "createdBy": "platform@orbyx.ai",
        "created": "Mar 25, 2026",
        "updated": "6d ago",
        "updatedFull": "Apr 3, 2026 · 10:55 UTC",
        "description": "Hard caps on token consumption: 8,192 tokens per session, 2M tokens per tenant per day. Soft warning at 80%. Prevents runaway LLM loops and controls API spend.",
        "affectedAssets": 9,
        "relatedAlerts": 0,
        "linkedSimulations": 0,
        "agents": [],
        "tools": [],
        "dataSources": [],
        "environments": ["Production", "Staging"],
        "exceptions": ["load-test-tenant"],
        "impact": {"blocked": 1, "flagged": 4, "unchanged": 95, "total": 100},
        "history": [
            {"version": "v1", "by": "platform@orbyx.ai", "when": "Mar 25, 2026 · 11:00", "change": "Initial token budget policy. Session cap 8192, daily tenant cap 2M."},
        ],
        "logic_code": _TOKEN_BUDGET_CODE,
        "logic_language": "json",
    },
    {
        "id": "of-v2",
        "name": "Output-Filter",
        "version": "v2",
        "type": "output-validation",
        "mode": "Enforce",
        "status": "Active",
        "scope": "All LLM Outputs",
        "owner": "security-ops",
        "createdBy": "sec-eng@orbyx.ai",
        "created": "Mar 18, 2026",
        "updated": "3d ago",
        "updatedFull": "Apr 6, 2026 · 08:40 UTC",
        "description": "Scans all LLM responses for secrets, credentials, and high-risk content before delivery. Blocks outputs containing credentials; redacts PII; blocks outputs flagged by secondary LLM scan.",
        "affectedAssets": 8,
        "relatedAlerts": 3,
        "linkedSimulations": 2,
        "agents": [],
        "tools": [],
        "dataSources": [],
        "environments": ["Production"],
        "exceptions": [],
        "impact": {"blocked": 2, "flagged": 6, "unchanged": 92, "total": 100},
        "history": [
            {"version": "v2", "by": "sec-eng@orbyx.ai", "when": "Apr 6, 2026 · 08:40", "change": "Added secondary LLM verdict check. Tightened redaction regex."},
            {"version": "v1", "by": "sec-eng@orbyx.ai", "when": "Mar 18, 2026 · 12:15", "change": "Initial output filter. Secret regex + PII redaction."},
        ],
        "logic_code": _OUTPUT_FILTER_CODE,
        "logic_language": "rego",
    },
    {
        "id": "ec-v1",
        "name": "Egress-Control",
        "version": "v1",
        "type": "data-access",
        "mode": "Monitor",
        "status": "Active",
        "scope": "External HTTP Calls",
        "owner": "network-security",
        "createdBy": "netops@orbyx.ai",
        "created": "Apr 1, 2026",
        "updated": "6d ago",
        "updatedFull": "Apr 3, 2026 · 17:00 UTC",
        "description": "Deny-by-default allowlist for agent egress. Controls which external endpoints agents may contact. Blocks known exfiltration channels (pastebin, requestbin, ngrok).",
        "affectedAssets": 4,
        "relatedAlerts": 1,
        "linkedSimulations": 0,
        "agents": ["ThreatHunter-AI", "DataPipeline-Orchestrator"],
        "tools": ["web.search", "web_fetch"],
        "dataSources": [],
        "environments": ["Production"],
        "exceptions": [],
        "impact": {"blocked": 0, "flagged": 2, "unchanged": 98, "total": 100},
        "history": [
            {"version": "v1", "by": "netops@orbyx.ai", "when": "Apr 1, 2026 · 09:00", "change": "Initial egress control policy. Allowlist: *.orbyx.internal, api.tavily.com, api.anthropic.com."},
        ],
        "logic_code": _EGRESS_CONTROL_CODE,
        "logic_language": "json",
    },
    {
        "id": "rr-v1",
        "name": "RAG-Retrieval-Limit",
        "version": "v1",
        "type": "data-access",
        "mode": "Monitor",
        "status": "Active",
        "scope": "RAG Pipeline",
        "owner": "platform-eng",
        "createdBy": "platform@orbyx.ai",
        "created": "Apr 2, 2026",
        "updated": "5d ago",
        "updatedFull": "Apr 4, 2026 · 13:30 UTC",
        "description": "Limits RAG retrieval chunk counts under elevated posture scores. Reduces context window to 3 chunks at posture ≥ 0.40 and blocks retrieval entirely at posture ≥ 0.70. Sensitive namespaces require explicit scope.",
        "affectedAssets": 3,
        "relatedAlerts": 0,
        "linkedSimulations": 1,
        "agents": ["CustomerSupport-GPT", "DataPipeline-Orchestrator"],
        "tools": [],
        "dataSources": ["knowledge-base", "customer-db"],
        "environments": ["Production", "Staging"],
        "exceptions": [],
        "impact": {"blocked": 1, "flagged": 3, "unchanged": 96, "total": 100},
        "history": [
            {"version": "v1", "by": "platform@orbyx.ai", "when": "Apr 2, 2026 · 10:00", "change": "Initial RAG retrieval limit. Sensitive namespace protection. Posture-gated chunk reduction."},
        ],
        "logic_code": _RAG_RETRIEVAL_CODE,
        "logic_language": "rego",
    },
    {
        "id": "jd-v2",
        "name": "Jailbreak-Detect",
        "version": "v2",
        "type": "prompt-safety",
        "mode": "Enforce",
        "status": "Active",
        "scope": "All User Inputs",
        "owner": "security-ops",
        "createdBy": "admin@orbyx.ai",
        "created": "Mar 16, 2026",
        "updated": "4d ago",
        "updatedFull": "Apr 5, 2026 · 11:00 UTC",
        "description": "Detects jailbreak attempts via pattern matching, Base64 payload detection, and threat score thresholding. Covers DAN variants, developer-mode prompts, roleplay overrides, and encoded bypass attempts.",
        "affectedAssets": 8,
        "relatedAlerts": 2,
        "linkedSimulations": 3,
        "agents": ["CustomerSupport-GPT", "ThreatHunter-AI"],
        "tools": [],
        "dataSources": [],
        "environments": ["Production"],
        "exceptions": ["red-team-agent"],
        "impact": {"blocked": 5, "flagged": 7, "unchanged": 88, "total": 100},
        "history": [
            {"version": "v2", "by": "admin@orbyx.ai",   "when": "Apr 5, 2026 · 11:00", "change": "Added Base64 payload heuristic. Expanded DAN variant signatures."},
            {"version": "v1", "by": "sec-eng@orbyx.ai", "when": "Mar 16, 2026 · 14:20", "change": "Initial jailbreak detection policy. Pattern library + threat score gate."},
        ],
        "logic_code": _JAILBREAK_DETECT_CODE,
        "logic_language": "rego",
    },
]


def seed_policies() -> None:
    """Insert default policies if the table is empty. Idempotent."""
    if list_policies():
        return
    for raw in _SEED_DATA:
        raw = dict(raw)  # don't mutate the module-level constant
        raw["logic"] = _tokenise(raw["logic_code"], raw["logic_language"])
        create_policy_raw(raw)
